import"./assets/styles-Dt4zwTEg.js";import{i as a,a as s}from"./assets/vendor-4yCzdkXl.js";function v(e,t,o){e.forEach(n=>{n.classList.remove(o)}),t.classList.add(o)}function T(e,t="success"){const o={message:e,position:"topRight",timeoot:5e3};switch(t){case"success":a.success(o);break;case"error":a.error(o);break;case"warning":a.warning(o);break;case"info":a.info(o);break;default:a.error({...o,message:"invalid type of tosat"});break}}const r={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),searchFormClearButton:document.querySelector(".search-form__btn-clear"),addToCartBtn:document.querySelector(".modal-product__btn--cart")};function k(){r.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden",document.addEventListener("keydown",y),r.modalCloseBtn.addEventListener("click",S),r.modal.addEventListener("click",L)}function h(){r.modal.classList.remove("modal--is-open"),document.body.style.overflow="",document.removeEventListener("keydown",y),r.modalCloseBtn.addEventListener("click",S),r.modal.addEventListener("click",L)}function y(e){e.code==="Escape"&&h()}function S(e){h()}function L(e){e.target===r.modal&&h()}const B="https://dummyjson.com",l={CATEGORIES:"/products/category-list",PRODUCTS:"/products",PRODUCTS_BY_CATEGORY:"/products/category/",PRODUCTS_BY_SEARCH:"/products/search",PRODUCT_BY_ID:"/products/"},R={CART:"cart",WHISHLIST:"whishlist",THEME:"theme"};s.defaults.baseURL=B;function $(){return s.get(l.CATEGORIES).then(({data:e})=>e)}function u(){return s.get(l.PRODUCTS).then(({data:e})=>e)}function A(e){return s.get(l.PRODUCTS_BY_CATEGORY+e).then(({data:t})=>t)}function I(e){return s.get(l.PRODUCT_BY_ID+e).then(({data:t})=>t)}function O(e){return s.get(`${l.PRODUCTS_BY_SEARCH}?q=${e}`).then(({data:t})=>t)}function D(e){const o=["All",...e].map(c=>`<li class="categories__item">
        <button class="categories__btn" type="button">${c}</button>
      </li>`).join("");r.categoriesList.innerHTML=o;const n=document.querySelector(".categories__btn");n&&n.classList.add("categories__btn--active")}function d(e){const t=e.map(({id:o,thumbnail:n,title:c,brand:p,category:g,price:i})=>`<li class="products__item" data-id="${o}">
        <img class="products__image" src="${n}" alt="${c}"/>
        <p class="products__title">${c}</p>
        <p class="products__brand">
        <span class="products__brand--bold">Brand: ${p}</span>
        </p>
        <p class="products__category">Category: ${g}</p>
        <p class="products__price">Price: ${i}$</p>
        </li>`).join("");r.productsList.insertAdjacentHTML("beforeend",t)}function H({thumbnail:e,title:t,category:o,description:n,price:c,shippingInformation:p,returnPolicy:g,tags:i}){const E=i?i.map(P=>`<li class="modal-product__tag">${P}</li>`).join(""):"",b=`
      <img class="modal-product__img" src="${e}" alt="${t}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${t}</p>
        <ul class="modal-product__tags">${E}</ul>
        <p class="modal-product__description">${n}</p>
        <p class="modal-product__shipping-information">Shipping: ${p}</p>
        <p class="modal-product__return-policy">Return Policy: ${g}</p>
        <p class="modal-product__price">Price: ${c}$</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;r.modalProduct.innerHTML=b}function f(){r.notFound.classList.remove("not-found--visible")}function m(){r.notFound.classList.add("not-found--visible")}function C(){r.productsList.innerHTML=""}function q(e){try{const t=localStorage.getItem(e);return t?JSON.parse(t):null}catch(t){return console.log("Error reading from Local Storage",t.message),null}}function F(){return q(R.CART)??[]}function M(e){return F().includes(e)}let _=null;function w(e){$().then(t=>{D(t)}).catch(t=>{console.log("Error on load Categories in Home page",t)}),u().then(({products:t})=>{d(t)}).catch(t=>{console.log("Error on load Products in Home page",t)})}function U(e){const t=e.target.closest(".categories__btn");if(!t)return;C();const o=r.categoriesList.querySelectorAll(".categories__btn");v(o,t,"categories__btn--active");const n=t.textContent.trim();u(),n==="All"?u().then(({products:c})=>{d(c)}).catch(c=>{console.log("Error on load Products in Home page",c)}):A(n).then(({products:c})=>{c.length>0?(d(c),f()):m()}).catch(c=>{console.log("Error on load Products by Category in Home page",c),m()})}function Y(e){const t=e.target.closest(".products__item");if(!t)return;const o=Number(t.dataset.id);_=o,I(o).then(n=>{k(),H(n)}).catch(n=>{console.log("Error on handleProductListClick",n)})}function N(e){e.preventDefault();const t=e.target.elements.searchValue.value.trim();if(t===""){T("enter a serch queary","warning");return}O(t).then(({products:o})=>{C(),o.length>0?(d(o),f()):m()}).catch(o=>{console.log("Error on handleSerchFormSubmit",o),m()})}function j(e){r.searchForm.reset(),C(),u().then(({products:t})=>{d(t),f()}).catch(t=>{console.log("Error on handleSerchClear",t)})}function G(e){_&&M(_)}document.addEventListener("DOMContentLoaded",w);r.categoriesList.addEventListener("click",U);r.productsList.addEventListener("click",Y);r.searchForm.addEventListener("submit",N);r.searchFormClearButton.addEventListener("click",j);r.addToCartBtn.addEventListener("click",G);
//# sourceMappingURL=index.js.map
