export const refs = {
  categoriesList: document.querySelector('.categories'),
  productsList: document.querySelector('.products'),
  notFound: document.querySelector('.not-found'),
  modal: document.querySelector('.modal'),
  modalProduct: document.querySelector('.modal-product'),
  modalCloseBtn: document.querySelector('.modal__close-btn'),
  searchForm: document.querySelector('.search-form'),
  searchFormClearButton: document.querySelector('.search-form__btn-clear'),
  addToCartBtn: document.querySelector('.modal-product__btn--cart'),
  addToWhishListBtn: document.querySelector('.modal-product__btn--wishlist'),
  loader: document.querySelector('.loader'),
  wishlistCount: document.querySelector('[data-wishlist-count]'),
  cartCount: document.querySelector('[data-cart-count]'),
};
